### ISSUE TITLE
Shadow effect in URL bar

### ISSUE THREAD

**Issue by jmseaton** [Lootyhoof/darkpitch#1]
I'm running 27.0 b1 32 bit on Win 7 x64.  All themes I've tried, but the default one, seem to have the shadow effect on text in the URL bar misplaced.  Please see attachment.  Since the issue doesn't occur in the base theme, I thought it may be something related to the themes.

![2016-10-04_13-04-34](https://cloud.githubusercontent.com/assets/3615288/19084101/220f6190-8a33-11e6-9de2-906353ed9f37.png)

**Comment by Lootyhoof** [comment]
Yes, I'm aware of this issue. I'm currently in the process of making the required changes to all themes I currently maintain, so please be patient while the fixes are applied.

Thanks!

**Comment by Lootyhoof** [comment]
Fixed as of https://github.com/Lootyhoof/darkpitch/commit/ab4e3797e7e341380ab8921771925e0d06c61666.
